### PR TITLE
Completed css-brochure-form exercise - Andrew Almeida

### PR DESCRIPTION
**Pull request by Andrew-M-A**
css-brochure-form

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Andrew! A few notes:
1. The borders on your form controls do not match the example.
2. The last label is centered rather than aligned left with a small indentation.
3. Your labels are too small as compared to the example
4. There should be some vertical space between the label and the form control element it is paired with.

Please revise and submit a new screenshot with your revision.

**Comment by Andrew-M-A** [comment]
css-brochure-form

**Review by codingcodymiller — APPROVED** [review]
Great work!!

**Comment by Andrew-M-A** [comment]
thank you sir !

**Pull request merged**
